name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    name: Tests (PHP ${{ matrix.php }}, Valgrind ${{ matrix.valgrind }}, Debug=${{ matrix.debug }}, ZTS=${{ matrix.zts }})
    strategy:
      fail-fast: false
      matrix:
        php: [8.0.13, 8.1.0]
        valgrind: [0, 1]
        debug: [enable, disable]
        zts: [on, off]

    steps:
      - uses: actions/checkout@v2

      - name: Install Valgrind
        if: matrix.valgrind == '1'
        run: |
          sudo apt-get update && sudo apt-get install valgrind
          echo "TEST_PHP_ARGS=-m" >> $GITHUB_ENV
          echo "PHP_BUILD_CONFIGURE_OPTS=--with-valgrind" >> $GITHUB_ENV

      - name: Install PHP dependencies
        run: sudo apt install libzip5

      - name: Restore PHP build cache
        uses: actions/cache@v2
        id: php-build-cache
        with:
          path: ${{ github.workspace }}/php 
          key: php-debug-${{ matrix.debug }}-${{ matrix.php }}-valgrind-${{ matrix.valgrind }}
  
      - name: Clone php-build repository
        if: steps.php-build-cache.outputs.cache-hit != 'true'
        uses: actions/checkout@v2
        with:
          repository: php-build/php-build
          path: php-build

      - name: Compile PHP
        if: steps.php-build-cache.outputs.cache-hit != 'true'
        run: |
          cd $GITHUB_WORKSPACE/php-build
          ./install-dependencies.sh
          PHP_BUILD_ZTS_ENABLE=${{ matrix.zts }} PHP_BUILD_CONFIGURE_OPTS="$PHP_BUILD_CONFIGURE_OPTS --${{ matrix.debug }}-debug" ./bin/php-build ${{ matrix.php }} $GITHUB_WORKSPACE/php

      - name: Compile extension
        run: |
          $GITHUB_WORKSPACE/php/bin/phpize
          ./configure --with-php-config=$GITHUB_WORKSPACE/php/bin/php-config
          make install

      - name: Generate php.ini
        run: |
          echo "extension=encoding.so" > $GITHUB_WORKSPACE/php.ini

      - name: Run PHPT tests
        run: |
          $GITHUB_WORKSPACE/php/bin/php ./run-tests.php $TEST_PHP_ARGS -P -q --show-diff --show-slow 30000 -n -c $GITHUB_WORKSPACE/php.ini

      - name: Upload test results
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: test-results-${{ matrix.php }}-valgrind-${{ matrix.valgrind }}
          path: |
            ${{ github.workspace }}/tests/*
            !${{ github.workspace }}/tests/*.phpt
